# Generated by Django 5.0.7 on 2024-07-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_price_purchase_buy_price_purchase_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
    ]
