# Generated by Django 5.0.7 on 2024-07-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_purchase_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='sell_price',
            new_name='sel_price',
        ),
    ]
