# Generated by Django 5.0.7 on 2024-07-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_purchase_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
    ]
