# Generated by Django 5.0.7 on 2024-08-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_purchase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='vsTokenSymbol',
            field=models.CharField(default='', max_length=255),
        ),
    ]
